#use_frameworks!
source 'https://github.com/chengzongxin/TMUICore.git'
source 'https://github.com/chengzongxin/TMUIExtensions.git'

platform :ios, '10.0'

target 'TMUIComponents_Example' do
  pod 'TMUIComponents', :path => '../'

  target 'TMUIComponents_Tests' do
    inherit! :search_paths

    
  end
end
